### ISSUE TITLE
Can't get with hex row key.

### ISSUE THREAD

**Issue by arisohn** [adaltas/node-hbase#23]
TEST table
 \xEE                                   column=c1:1234, timestamp=1405787868039, value=1234                                                               

  var assert = require('assert');
  var hbase = require('hbase');

  hbase({host: '192.168.1.1', port: 8080})
          .getRow('TEST','\xEE')
          .get('c1:1234', function(error, value){
                  console.log(value);
          }
  );

this doesn't work properly.

**Comment by cccvvv2012** [comment]
This works for me with latest codes
hbase({host: 'localhost', port: 8080})
    .table('TEST')
    .row('\xEE')
    .get('c1:1234', function(error, value){
        console.log(value);
    }
);

**Comment by wdavidw** [comment]
Old issue, closing.
