### ISSUE TITLE
scan seems to be broken...

### ISSUE THREAD

**Issue by acourtois** [adaltas/node-hbase#25]
I'm trying tu use the scan to retreive data with filters (I want to get columns which names has a timestamp prefix from a date to another date from 1 row). I manage to configure the scanner and its filter but can't get the results... Here is my code:

```
var TABLE = 'myTable';
var TEST_KEY = 'myRowKey';
var FROM = '2014-01-01';
var TO = '2014-12-31';

var scannerFilter = {
        "op" : "MUST_PASS_ALL",
        "type" : "FilterList",
        "filters" : [
            {
                "type": "RowFilter",
                "op": "EQUAL",
                "comparator": {
                    "type": "BinaryComparator",
                    "value": TEST_KEY
                }
            },
            {
                "type": "ColumnRangeFilter",
                "minColumn": FROM,
                "minColumnInclusive": true,
                "maxColumn": TO,
                "maxColumnInclusive": true
            }
        ]
    };

var scannerOptions = {
        table : TABLE,
        encoding: 'utf-8',
        maxVersion: 1,
        filter: scannerFilter
    };

client.table(TABLE)
        .scan(scannerOptions, function(err, rows){
            console.log(err, rows);
        });
```

`rows.length` is correct. But rows is an array of string... and these strings are (and it's really a string!!) `[object Object]` !

I probably miss something. I tried a lot of things:
- in table.js, line 315 (in Table.prototype.scan): adding `console.log(chunk)` after `while (chunk = scanner.read()) {` => chunk is a string [object Object] 
- in scanner.js, line 211 (in Scanner.prototype.get): adding `console.log(data)` before `return cells.push(data);` => data is the JSON object I want
- in scanner.js, line 284 (Scanner.prototype._read): adding `console.log(cell)` after `cell = cells[_i];` => cell is the JSON object I want
- in scanner.js, line 286 (Scanner.prototype._read): adding `console.log(_results)` before `return _results;` => _results is an array of boolean  

I did not understand what's wrong... Any idea?

I'm using:
- nodeJS v0.10.36
- Install node-hbase with `npm install hbase`

**Comment by wdavidw** [comment]
i will look at it but i need a week. i'm currently upgrade ryba to support hdp2.2 and i need a local working hbase instance first

**Comment by cccvvv2012** [comment]
you must use full name of column name otherwise you have to use
QualifierFilter and RegexStringComparator (in my understanding or have better solution)
also you should encoding with base64 when use 
for example
```javascript
var hbase = require('hbase');
var hbaseUtils = hbase.utils;
var scannerFilter = {
        "op" : "MUST_PASS_ALL",
        "type" : "FilterList",
        "filters" : [
            {
                "type": "RowFilter",
                "op": "EQUAL",
                "comparator": {
                    "type": "BinaryComparator",
                    "value": TEST_KEY
                }
            },
            {
                "type": "ColumnRangeFilter",
                "minColumn": hbaseUtils.base64.encode(FROM),
                "minColumnInclusive": true,
                "maxColumn": hbaseUtils.base64.encode(TO),
                "maxColumnInclusive": true
            }
        ]
    };
```

**Comment by yellowbrickc** [comment]
@acourtois we just had the same problem. The problem is in scanner:

> data.Row.forEach(function(row) {
        key = utils.base64.decode(row.key, _this.client.options.encoding);
        return row.Cell.forEach(function(cell) {
          data = {};
          data.key = key;
          data.column = utils.base64.decode(cell.column, _this.client.options.encoding);
          data.timestamp = cell.timestamp;
          data.$ = utils.base64.decode(cell.$, _this.client.options.encoding);
          return cells.push(data);
        });
      });

The scanner uses only the options from the client and not from the scanner itself. Configure your client to have the encoding option and it should work. It did for me :)

**Comment by wdavidw** [comment]
could u provide a fix ?

**Comment by yellowbrickc** [comment]
I will try to fix it tomorrow but the code works already if the encoding option is set only for the client and not for the scanner. (Actually I'm not really sure why should the scanner allow encoding options by himself? )

**Comment by wdavidw** [comment]
Scan has been fix a few weeks ago. Old issue, closing.
