### ISSUE TITLE
.getTable( 'my_table' ) TypeError: undefined is not a function

### ISSUE THREAD

**Issue by earthican** [adaltas/node-hbase#30]
Hi,
I am getting an issue when trying to get a table from my client. My code is as follows:

``` javascript
  hbase({ host: '127.0.0.1', port: 8080 })
  .getTable( 'websites' )
  .getSchema(function(error, schema){
    console.log(schema);
  });
```

and these are the errors that follow:

```
.getTable( 'websites' )
   ^
TypeError: undefined is not a function
```

Is there another way of getting a table?

**Comment by bumrush** [comment]
This code works:
```javascript
hbase({ host: '127.0.0.1', port: 8080 })
  .table( 'websites' )
  .schema(function(error, schema){
    console.log(schema);
  });
```
Seems like there aren't anymore 'getters'. Is it possible to get the documentation updated?

**Comment by wdavidw** [comment]
I dont have much time at the moment.

**Comment by bumrush** [comment]
No problem, thanks for the update. I will be playing around with your module over the next couple weeks, so I might just submit a pull request.

**Comment by wdavidw** [comment]
that would be perfect

**Comment by wdavidw** [comment]
Old issue, closing.
