### ISSUE TITLE
unable to connect to hbase server using nodejs

### ISSUE THREAD

**Issue by RAKESH1256** [adaltas/node-hbase#32]
var hbase = require('hbase');
hbase({
    host: 'host.com',
    port: 22,
    timeout: 6000,
    "krb5": {
        "principal": "username@username",
        "password": "password@password"
    }
})
.table('emp')
.scan({
    startRow: 'name',
    maxVersions: 1
}, function (err, rows) {
    console.log(err, rows);
});

**Comment by wdavidw** [comment]
krb5 shall look like:

```
  "krb5": {
    "principal": "ryba@HADOOP.RYBA",
    "password": "test123",
    "service_principal": "HTTP@master3.ryba"
  }
```

**Comment by IDerr** [comment]
I think you can close this @wdavidw
