### ISSUE TITLE
Assertion error when trying to connec to hbase

### ISSUE THREAD

**Issue by seleregb** [adaltas/node-hbase#37]
I have hadoop and hbase 1.1.2 set up on my vmware ubuntu system. I am trying to connect to hbase to insert a table with rows but keep ending up with an assertion error. I am using the sample code from the npm package website:

<pre><code>
var assert = require('assert');
var hbase = require('hbase');
 
hbase({ host: '127.0.0.1', port: 8080 })
.table('my_table' )
.create('my_column_family', function(err, success){
  this
  .row('my_row')
  .put('my_column_family:my_column', 'my value', function(err, success){
    this.get('my_column_family', function(err, cells){
      this.exists(function(err, exists){
        assert.ok(exists);
      });
    });
  });
});
</code></pre>

**Comment by wdavidw** [comment]
what is your error?

**Comment by seleregb** [comment]
Sorry for the late reply. I get this error:

<pre><code>
assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: null == true
    at null.<anonymous> (/home/tentacleproj/Documents/Node.js/visualize_data_with_d3.js/startupdemo/app.js:12:16)
    at /home/tentacleproj/Documents/Node.js/visualize_data_with_d3.js/startupdemo/node_modules/hbase/lib/row.js:186:22
    at ClientRequest.<anonymous> (/home/tentacleproj/Documents/Node.js/visualize_data_with_d3.js/startupdemo/node_modules/hbase/lib/connection.js:96:16)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)

</code></pre>

**Comment by wdavidw** [comment]
this error is thrown in your code, i need one thrown inside the driver.

**Comment by seleregb** [comment]
And what is the error with the code?? You have clearly indicated in the description for this package, that this is the syntax to create a hbase table with a column family, and I have followed that but keep coming up with the same error. I also started the hbase thrift server and changed the port but that doesn't also work.

**Comment by wdavidw** [comment]
Whatever u got on line 12 is not my conserne. U shall start and connect to the rest server

**Comment by IDerr** [comment]
You can close this @wdavidw
