### ISSUE TITLE
Connection Time Out Handling 

### ISSUE THREAD

**Issue by sohimankotia** [adaltas/node-hbase#40]
Hi ,Is there any timeout handling or option we can set. As if Hbase is not responding for request for log time node js client still waiting for that .

Thanks in advance

**Comment by wdavidw** [comment]
Looking at the Node.js [HTTP documentation](https://nodejs.org/api/http.html#http_request_settimeout_timeout_callback), there seems to exist a `setTimeout` function. Feel free to submit a pull request with the functionnality and its associated test.

**Comment by eaielo** [comment]
there is not exist setTimeout function，should implement it by yourself， i'd prefer the third party request librery. Professional handles professional affairs.

**Comment by wdavidw** [comment]
Old issue, closing.
