### ISSUE TITLE
does it support mget, checkAndPut, incrementColumnValue?

### ISSUE THREAD

**Issue by cosdy** [adaltas/node-hbase#45]
like the https://github.com/falsecz/hbase-rpc-client

**Comment by wdavidw** [comment]
I thing it supports the `mget` operation as illustrated in this [test](https://github.com/adaltas/node-hbase/blob/master/test/row.coffee#L231-L237). I'm not sure the `checkAndPut` is exposed by the REST API. At least it wasn't available at the time I wrote the driver. Also it is probably replaced by an HTTP status code. As for the `incrementColumnValue`, it is not implemented, it didn't exist at the time.
