### ISSUE TITLE
do not set default port if not set

### ISSUE THREAD

**Issue by yellowbrickc** [adaltas/node-hbase#50]
Hi,
we use an HBase/Rest-Service on AWS and we don't have a port to supply as option. What do you think about the idea to only set the fallback if the host is missing too or is set to localhost?

We would implement this if it's ok for you.

Cheers

**Comment by wdavidw** [comment]
Hi, what do you mean by "we don't have a port to supply as option"

**Comment by yellowbrickc** [comment]
I meant fix endpoints, without a port.
Doesn't matter anyway, [PR52](https://github.com/adaltas/node-hbase/pull/52) fixes this problem. 
BTW the issuer kubikb is my colleague :)

It would be cool if you could release a new npm-package during this week.
Thanks a lot.

**Comment by wdavidw** [comment]
Great, he did a fantastic job. I wasn't sure what you meant by endpoint, the URL ? Glad that the issue is fixed. The release is published
