### ISSUE TITLE
User customization of HTTP(S) request options

### ISSUE THREAD

**Issue by kubikb** [adaltas/node-hbase#53]
Hello,
since HBase REST may run in many different settings, node-hbase should enable the user to pass options to HTTP(S) requests. For example, node-hbase can only handle HBase REST if it is accessed through the base URL, SSL certificates cannot be passed to the HTTPS requests, etc. The inability to customize connections limits the usability of this package.
To overcome this limitation, I propose that the options object passed to the Client class should be passed to the Connection class while preserving the properties necessary for node-hbase's operation. Although I understand the rationale of abstracting away the specifics of making HTTP(S) requests, the multitude of possible HBase REST configurations may require more control (and responsibility) over these requests from the user's side. For example, the HBase REST I use can be accessed through an nginx reverse proxy that requires a specific path and client-side SSL authentication.
What do you think? I submitted a PR with the proposed changes: https://github.com/adaltas/node-hbase/pull/52. Could you take a look at it? I did some refactoring to make the Connection object more (unit)testable, added tests, added a Docker image based on `sixeyed/hbase-stargate` with an nginx reverse proxy to test custom paths, and also modified the Jenkins build accordingly.

**Comment by kubikb** [comment]
Closing this issue since the changes have been merged (https://github.com/adaltas/node-hbase/pull/52). Thanks!

**Comment by kubikb** [comment]
The possibility to append custom values to HTTP(S) request headers should also be made possible. I submitted a new pull request that adds this functionality: https://github.com/adaltas/node-hbase/pull/54

**Comment by kubikb** [comment]
If you agree, could you also create a new release so that it is published to npm?

**Comment by wdavidw** [comment]
It was goal until i fall asleep, i'll integrate #54 before

**Comment by kubikb** [comment]
Thanks!
