### ISSUE TITLE
How can I get Buffer type data from hbase

### ISSUE THREAD

**Issue by gofordream** [adaltas/node-hbase#57]
My code like this:
table('tableName').row('rowkey').get("cf:col",function(err,value){});
the typeof value is string, how can I get Buffer type?

**Comment by wdavidw** [comment]
This is not supported a the moment, I agree this should be the default type. Feel free to contribute to this request, it would make sense

**Comment by gofordream** [comment]
There is a cell in my hbase and the value is : 
1f 8b 8 0 0 0 0 0 0 13 ab 56 ca 4b cc 4d 55 b2 52 ca cd ce 4c 55 aa 5 0 5c 4c 89 f3 f 0 0 0
I can use java api to get these bytes, but when I use node-hbase, I get a string of 35 length. Then I print it this way:
var databuff=new Buffer(datastr,"binary");
console.log(databuff)
The output like this:
<Buffer 1f fd 08 00 00 00 00 00 00 13 fd 56 fd 4b fd 4d 55 fd 52 fd fd fd 4c 55 fd 05 00 5
c 4c fd fd 0f 00 00 00>
It is different from the value in my base:
<Buffer 1f fd 08 00 00 00 00 00 00 13 fd 56 fd 4b fd 4d 55 fd 52 fd fd fd 4c 55 fd 05 00 5
c 4c fd fd 0f 00 00 00>
How can I get same value?

**Comment by gofordream** [comment]
how to set time-out?

**Comment by wdavidw** [comment]
Closing and opening a new issue for the timeout option
