### ISSUE TITLE
How to fetch different version from hbase?

### ISSUE THREAD

**Issue by ThreeFireLee** [adaltas/node-hbase#62]
I do not find any function about how to fetch data with different version

**Comment by ZuxiangWu** [comment]
I have the same problem, how do I get different cell versions ?

**Comment by wdavidw** [comment]
Sorry that I didn't get back to you on time. This test case illustrates who to [fetch multiple versions](https://github.com/adaltas/node-hbase/blob/master/test/scanner.coffee#L143-L152).
