### ISSUE TITLE
hbase-rest-reverse-proxy can't used

### ISSUE THREAD

**Issue by YSHIDM** [adaltas/node-hbase#64]
const hbase = require('hbase');
client = hbase({ host: '127.0.0.1', port: 8080 });
client
.table('my_table' )
.create('my_column_family', function(err, success){
//success===null why???
})
------------------------------------------------
what's the matter?
![2019-02-20_015406](https://user-images.githubusercontent.com/7659872/53037503-59184b00-34b5-11e9-9494-b85961d1b672.jpg)

**Comment by IDerr** [comment]
Hello,
the creator of the base image this repo is using has been deleted/ made private.

I'll push a fix to use an another image.

Thanks for your report :)

**Comment by wdavidw** [comment]
@IDerr which image? The "nerdammer/hbase:1.1.2" is till online no?

**Comment by IDerr** [comment]
Not the one used for the reverse proxy. 
fork-hbase-rest

**Comment by wdavidw** [comment]
That was ours when "nerdammer/hbase:1.1.2" was using centos 6, no? He accepted my pull request on GitHub a few months/years ago but I just noticed that the Dockerfile on Docker Hub is still mentioning Centos 6

**Comment by IDerr** [comment]
hmm, I have pushed a fix to use the older image you were using (sixeyed).
Do you want me to revert my fix and use "nerdammer/hbase:1.1.2" as base image ?

**Comment by wdavidw** [comment]
That would explain why we are now referencing an image which noone can build anymore

**Comment by IDerr** [comment]
Not at all, it seems that it is a image built by us as referenced here : 
https://hbase.js.org/learn/developer/
```
# Build the REST image
docker build -t fork-hbase-rest docker/hbase-rest
```

**Comment by wdavidw** [comment]
Nope, I did not pushed it, it is meant to be built and used locally.

**Comment by YSHIDM** [comment]
Ok,thanks.
